# Generated by Django 3.1.5 on 2021-12-19 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import homepage.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberTracking', models.IntegerField(default=1)),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('country', django_countries.fields.CountryField(countries=homepage.models.supportedCountries, max_length=2, null=True)),
                ('name', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productURL', models.URLField(default='', max_length=60000)),
                ('productNAME', models.CharField(default='', max_length=500)),
                ('productDATE', models.DateTimeField(auto_now_add=True)),
                ('productIMAGE', models.URLField(default='', max_length=10000)),
                ('productRRP', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('productPRICE', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('offersUsedProductPRICE', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('offersNewProductPRICE', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('productMANUFACTURE', models.CharField(default='', max_length=9999999, null=True)),
                ('productBRAND', models.CharField(default='', max_length=9999999, null=True)),
                ('productMODEL', models.CharField(default='', max_length=9999999, null=True)),
                ('productCONDITON', models.CharField(default='', max_length=9999999, null=True)),
                ('productMERCHANT', models.CharField(default='', max_length=9999999, null=True)),
                ('productPRODUCTGROUP', models.CharField(default='', max_length=9999999, null=True)),
                ('productASIN', models.CharField(default='', max_length=9999999, null=True)),
                ('productCOUNTRY', django_countries.fields.CountryField(countries=homepage.models.supportedCountries, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminderPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.product')),
            ],
        ),
    ]
