# Generated by Django 3.1.5 on 2021-12-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='reminderType',
            field=models.CharField(blank=True, choices=[('Email', 'Email'), ('Phone Number', 'Phone Number')], max_length=13),
        ),
    ]
