# Generated by Django 3.1.5 on 2021-12-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_tracker_remindertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='reminderPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
