# Generated by Django 3.1.5 on 2022-03-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20211219_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminderPriceDB', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reminderTypeDB', models.CharField(blank=True, choices=[('Email', 'Email'), ('Phone', 'Phone')], max_length=13)),
            ],
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='reminderPrice',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='reminderType',
        ),
    ]
