# Generated by Django 3.1.5 on 2022-03-10 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20220310_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.customer'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.product'),
        ),
    ]
